# Generated by Django 3.2.3 on 2021-05-30 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('driving_licence_number', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(16)])),
                ('test_ref', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('recent_test_failure', models.DateField(blank=True, null=True)),
                ('earliest_test_date', models.DateField(default=django.utils.timezone.now)),
                ('latest_test_date', models.DateField(blank=True, null=True)),
                ('last_crawled', models.TimeField(blank=True, null=True)),
                ('info_validation', models.CharField(choices=[('unchecked', 'unchecked'), ('valid', 'valid'), ('invalid', 'invalid')], default='unchecked', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ip', models.CharField(max_length=30, unique=True)),
                ('last_used', models.TimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now_add=True)),
                ('customers', models.ManyToManyField(blank=True, to='api.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='main_test_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.testcenter'),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_time', to='api.availabledate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='availabledate',
            name='test_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='api.testcenter'),
        ),
        migrations.CreateModel(
            name='AcceptableTimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptable_time_ranges', to='api.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
