# Generated by Django 3.2.3 on 2021-05-22 23:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driving_licence_number', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('test_ref', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('earliest_test_date', models.DateField(blank=True)),
                ('latest_test_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('customers', models.ManyToManyField(to='api.Customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='main_test_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.testcenter'),
        ),
        migrations.CreateModel(
            name='AcceptableTimeRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
