# Generated by Django 3.2.3 on 2021-05-23 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptabletimerange',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptable_time_ranges', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='testcenter',
            name='customers',
            field=models.ManyToManyField(blank=True, to='api.Customer'),
        ),
    ]
