# Generated by Django 3.2.3 on 2021-05-30 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210530_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_crawled',
            field=models.TimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_used',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
