# Generated by Django 3.2.3 on 2021-06-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='main_test_center',
        ),
        migrations.RemoveField(
            model_name='testcenter',
            name='customers',
        ),
        migrations.AddField(
            model_name='profile',
            name='test_centers',
            field=models.ManyToManyField(blank=True, to='api.TestCenter'),
        ),
    ]
