# Generated by Django 3.2.3 on 2021-05-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_availabledate_availabletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabledate',
            name='test_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_dates', to='api.testcenter'),
        ),
    ]
