# Generated by Django 3.2.3 on 2021-05-31 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210530_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_crawled',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='last_used',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
