# Generated by Django 3.2.3 on 2021-06-22 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 16, 48, 23, 743427, tzinfo=utc)),
        ),
    ]
