# Generated by Django 3.2.3 on 2021-05-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210531_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='automatic_booking',
            field=models.BooleanField(default=False),
        ),
    ]
