# Generated by Django 3.2.3 on 2021-06-22 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_token_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 21, 40, 32, 769478, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
