# Generated by Django 3.2.3 on 2021-05-26 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_latest_test_date_availabledate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='earliest_test_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
