# Generated by Django 3.2.3 on 2021-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_customer_automatic_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
