# Generated by Django 3.2.3 on 2021-06-22 21:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210622_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 22, 16, 50, 495522, tzinfo=utc)),
        ),
    ]
