# Generated by Django 3.2.3 on 2021-05-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customer_recent_test_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='recent_test_failure',
            field=models.DateField(blank=True, null=True),
        ),
    ]
