# Generated by Django 3.2.3 on 2021-05-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customer_recent_test_failure'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='info_valid',
            field=models.CharField(choices=[('unchecked', 'unchecked'), ('valid', 'valid'), ('valid', 'invalid')], default='unchecked', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latest_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
