# Generated by Django 3.2.3 on 2021-06-24 22:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210623_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theory_test_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 24, 23, 55, 49, 532736, tzinfo=utc)),
        ),
    ]
