# Generated by Django 3.2.3 on 2021-05-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210526_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='info_valid',
            new_name='info_validation',
        ),
    ]
