# Generated by Django 3.2.3 on 2021-06-25 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210624_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 25, 16, 5, 52, 81301, tzinfo=utc)),
        ),
    ]
