# Generated by Django 3.2.3 on 2021-05-27 02:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_info_valid_customer_info_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcenter',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='info_validation',
            field=models.CharField(choices=[('unchecked', 'unchecked'), ('valid', 'valid'), ('invalid', 'invalid')], default='unchecked', max_length=20),
        ),
    ]
