# Generated by Django 3.2.3 on 2021-06-26 18:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210625_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='use_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 19, 23, 8, 625710, tzinfo=utc)),
        ),
    ]
