# Generated by Django 3.2.3 on 2021-06-10 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210610_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='earliest_test_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
