# Generated by Django 3.2.3 on 2021-06-28 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210626_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 28, 23, 49, 16, 544222, tzinfo=utc)),
        ),
    ]
